#!/bin/bash
make -f rucrclib.mak clean
make -f walklib.mak clean
make -f rucrcraw.mak clean
make -f rucrcgen.mak clean
make -f rucrctim.mak clean
make -f rucrcdots.mak clean
make -f binom.mak clean
make -f captcha.mak clean
make -f rucrcencr.mak clean
make -f rucrcnorm.mak clean
make -f rucrcpat.mak clean
make -f genalfa.mak clean
make -f gendna.mak clean
make -f pair.mak clean
make -f mcbell.mak clean
make -f mchain.mak clean
make -f mccos.mak clean
make -f mcparab.mak clean
make -f mcpi.mak clean
make -f mcsin.mak clean
make -f mcsph.mak clean
make -f poischi.mak clean
make -f pwrball.mak clean
make -f qmatch.mak clean
make -f ranwlk.mak clean
make -f tstrucrc.mak clean
make -f uintchi.mak clean
