#!/bin/bash
make -f rucrclib.mak
make -f walklib.mak
make -f rucrcraw.mak
make -f rucrcgen.mak
make -f rucrctim.mak
make -f rucrcdots.mak
make -f binom.mak
make -f captcha.mak
make -f rucrcencr.mak
make -f rucrcnorm.mak
make -f rucrcpat.mak
make -f genalfa.mak
make -f gendna.mak
make -f pair.mak
make -f mcbell.mak
make -f mchain.mak
make -f mccos.mak
make -f mcparab.mak
make -f mcpi.mak
make -f mcsin.mak
make -f mcsph.mak
make -f poischi.mak
make -f pwrball.mak
make -f qmatch.mak
make -f ranwlk.mak
make -f tstrucrc.mak
make -f uintchi.mak
